version: "3"

volumes:
  spg-data: {}
  sc-data: {}
services:
  superset-postgres:
    image: centos/postgresql-10-centos7:1
    volumes:
      - spg-data:/var/lib/pgsql/data:Z
    environment:
      - POSTGRESQL_USER=pg_user
      - POSTGRESQL_PASSWORD=pg_password
      - POSTGRESQL_DATABASE=superset
    ports: 
      - "5432:5432"
  superset-redis:
    image: centos/redis-32-centos7:3.2
    volumes:
      - sc-data:/var/lib/redis/data:Z
    ports: 
      - "6379:6379"
  superset-0:
    image: irfius/s2i-superset:0.28.1
    environment: 
      - cmd=superset-init
    ports: 
      - "8088:8088"
      - "6666:6666"
      - "8125:8125"
  superset-1:
    image: irfius/s2i-superset:0.28.1
    environment: 
      - cmd=superset
    ports: 
      - "8088:8088"
      - "6666:6666"
      - "8125:8125"
