version: "3"

volumes:
  spg-data: {}
  sc-data: {}

services:
  superset-postgres:
    image: centos/postgresql-10-centos7:1
    volumes:
      - spg-data:/var/lib/pgsql/data:Z
    environment:
      - POSTGRESQL_USER=superset_user
      - POSTGRESQL_PASSWORD=superset_password
      - POSTGRESQL_DATABASE=superset
    ports: 
      - "5432:5432"
  superset-redis:
    image: centos/redis-32-centos7:3.2
    volumes:
      - sc-data:/var/lib/redis/data:Z
    ports: 
      - "6379:6379"
  superset:
    image: irfius/s2i-superset:0.34.0
    environment: 
      - cmd=superset-init
      - POSTGRESQL_USER=superset_user
      - POSTGRESQL_PASSWORD=superset_password
      - POSTGRESQL_DATABASE=superset
      - POSTGRESQL_HOST=superset-postgres
      - REDIS_HOST=superset-redis
      - fab_username=admin
      - fab_firstname=admin
      - fab_lastname=minda
      - fab_email=admin@example.com
      - fab_password=password
    ports: 
      - "8088:8088"
      - "8081:8081"
      - "8125:8125"
    links: 
      - superset-postgres
      - superset-redis
